## Objective
- Detect Fake and Real Notes on basis of features

# Keras Basics

Welcome to the section on deep learning! We'll be using Keras with a TensorFlow backend to perform our deep learning operations.

This means we should get familiar with some Keras fundamentals and basics!

## Imports



In [4]:
import numpy as np

## Dataset

We will use the Bank Authentication Data Set to start off with. This data set consists of various image features derived from images that had 400 x 400 pixels. You should note **the data itself that we will be using ARE NOT ACTUAL IMAGES**, they are **features** of images. In the next lecture we will cover grabbing and working with image data with Keras. This notebook focuses on learning the basics of building a neural network with Keras.

_____
More info on the data set:

https://archive.ics.uci.edu/ml/datasets/banknote+authentication

Data were extracted from images that were taken from genuine and forged banknote-like specimens. For digitization, an industrial camera usually used for print inspection was used. The final images have 400x 400 pixels. Due to the object lens and distance to the investigated object gray-scale pictures with a resolution of about 660 dpi were gained. Wavelet Transform tool were used to extract features from images.


Attribute Information:

1. variance of Wavelet Transformed image (continuous)
2. skewness of Wavelet Transformed image (continuous)
3. curtosis of Wavelet Transformed image (continuous)
4. entropy of image (continuous)
5. class (integer)

## Reading in the Data Set

We've already downloaded the dataset, its in the DATA folder. So let's open it up.

In [5]:
from numpy import genfromtxt

In [6]:
data=genfromtxt('bank_note_data.txt',delimiter=',') # delimiter added beacuse this is preloaded data so it needs such features
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [7]:
labels=data[:,4] #Target

In [8]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

## Feature Extraction

In [9]:
features=data[:,0:4]  #Features

In [10]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [11]:
X=features
y=labels

## **Split Data into Train and Test**

Its time to split the data into a train/test set. Keep in mind, sometimes people like to split 3 ways, train/test/validation. We'll keep things simple for now. **Remember to check out the video explanation as to why we split and what all the parameters mean!**

In [12]:
from  sklearn.model_selection import train_test_split

In [13]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
#Random state=0 : seed Value meaning it will keep X_train data as it kept before

### **Standardization**

In [14]:
from sklearn.preprocessing import MinMaxScaler

Usually when using Neural Networks, you will get better performance when you standardize the data. Standardization just means normalizing the values to all fit between a certain range, like 0-1, or -1 to 1.

The scikit learn library also provides a nice function for this.

http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html

#### **Scaled X_train**

In [15]:
#intializing Object
min_max=MinMaxScaler()

Scaled_X_train=min_max.fit_transform(X_train)

In [16]:
X_train

array([[-1.3885  , 12.5026  ,  0.69118 , -7.5487  ],
       [ 2.7744  ,  6.8576  , -1.0671  ,  0.075416],
       [-4.2887  , -7.8633  , 11.8387  , -1.8978  ],
       ...,
       [-7.0364  ,  9.2931  ,  0.16594 , -4.5396  ],
       [-3.4605  ,  2.6901  ,  0.16165 , -1.0224  ],
       [-3.3582  , -7.2404  , 11.4419  , -0.57113 ]])

In [17]:
Scaled_X_train

array([[4.07704678e-01, 9.83199063e-01, 2.56697443e-01, 9.33178971e-02],
       [7.07908761e-01, 7.71971248e-01, 1.80872580e-01, 8.05140280e-01],
       [1.98559159e-01, 2.21136252e-01, 7.37428144e-01, 6.20911798e-01],
       ...,
       [4.11050776e-04, 8.63104170e-01, 2.34046756e-01, 3.74261253e-01],
       [2.58284115e-01, 6.16029366e-01, 2.33861752e-01, 7.02643151e-01],
       [2.65661395e-01, 2.44444278e-01, 7.20316361e-01, 7.44775785e-01]])

#### **Scale X_test**

In [18]:
#intializing Object
min_max=MinMaxScaler()
Scaled_X_test=min_max.fit_transform(X_test)

In [19]:
Scaled_X_test

array([[0.65576832, 0.76019778, 0.24484009, 0.52394294],
       [0.51021119, 0.83150383, 0.1032605 , 0.51241232],
       [0.53621584, 0.78751834, 0.15506107, 0.45135977],
       ...,
       [0.8049803 , 0.34220013, 0.42357773, 0.77514695],
       [0.51021277, 0.83150383, 0.1032605 , 0.51241232],
       [0.7514342 , 0.93958965, 0.08295672, 0.3285983 ]])

## **Building Neaural Network**

In [20]:
from keras.models import Sequential
from keras.layers import Dense


#### **Adding Hidden Layers**

In [21]:
model=Sequential()
# 8 Neurons, expects input of 4 features.
# Play around with the number of neurons!!
#First Layer
model.add(Dense(4,input_dim=4,activation='relu'))
# Add another Densely Connected layer (every neuron connected to every neuron in the next layer)
#Second Layer
model.add(Dense(8,activation='relu'))
# Last layer simple sigmoid function to output 0 or 1 (our label)
#Output Layer
model.add(Dense(1,activation='sigmoid'))  #Binary Classification ,yes or No

#### **Compiling the Model**

In [22]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
#binary Classification we use  binary_crossentropy

### **Training Model**

In [24]:
model.fit(Scaled_X_train,y_train,epochs=50,verbose=2)
#epochs is the number of time data will be passed through model
#verbose is the way it is written while compiling

Epoch 1/50
35/35 - 0s - loss: 0.2832 - accuracy: 0.9116 - 64ms/epoch - 2ms/step
Epoch 2/50
35/35 - 0s - loss: 0.2697 - accuracy: 0.9198 - 62ms/epoch - 2ms/step
Epoch 3/50
35/35 - 0s - loss: 0.2582 - accuracy: 0.9262 - 66ms/epoch - 2ms/step
Epoch 4/50
35/35 - 0s - loss: 0.2482 - accuracy: 0.9280 - 64ms/epoch - 2ms/step
Epoch 5/50
35/35 - 0s - loss: 0.2380 - accuracy: 0.9389 - 73ms/epoch - 2ms/step
Epoch 6/50
35/35 - 0s - loss: 0.2286 - accuracy: 0.9398 - 91ms/epoch - 3ms/step
Epoch 7/50
35/35 - 0s - loss: 0.2201 - accuracy: 0.9426 - 84ms/epoch - 2ms/step
Epoch 8/50
35/35 - 0s - loss: 0.2122 - accuracy: 0.9462 - 67ms/epoch - 2ms/step
Epoch 9/50
35/35 - 0s - loss: 0.2041 - accuracy: 0.9462 - 62ms/epoch - 2ms/step
Epoch 10/50
35/35 - 0s - loss: 0.1972 - accuracy: 0.9462 - 77ms/epoch - 2ms/step
Epoch 11/50
35/35 - 0s - loss: 0.1895 - accuracy: 0.9499 - 60ms/epoch - 2ms/step
Epoch 12/50
35/35 - 0s - loss: 0.1823 - accuracy: 0.9426 - 81ms/epoch - 2ms/step
Epoch 13/50
35/35 - 0s - loss: 0.1767

In [25]:
Scaled_X_test

array([[0.65576832, 0.76019778, 0.24484009, 0.52394294],
       [0.51021119, 0.83150383, 0.1032605 , 0.51241232],
       [0.53621584, 0.78751834, 0.15506107, 0.45135977],
       ...,
       [0.8049803 , 0.34220013, 0.42357773, 0.77514695],
       [0.51021277, 0.83150383, 0.1032605 , 0.51241232],
       [0.7514342 , 0.93958965, 0.08295672, 0.3285983 ]])

## Predicting New Unseen Data

Let's see how we did by predicting on **new data**. Remember, our model has **never** seen the test data that we scaled previously! This process is the exact same process you would use on totally brand new data. For example , a brand new bank note that you just analyzed .

In [26]:
predictions=model.predict(Scaled_X_test)

9/9 [==============================] - 0s 3ms/step


In [38]:
# Print the predicted probabilities for the first 5 samples
print(predictions[:5])

[[0.00339655]
 [0.26251358]
 [0.07482662]
 [0.0149166 ]
 [0.00241024]]


In [29]:
predictions   #Proability for real or fake
# 0 & 1

array([[3.3965462e-03],
       [2.6251358e-01],
       [7.4826621e-02],
       [1.4916598e-02],
       [2.4102428e-03],
       [8.7553903e-04],
       [9.8309750e-03],
       [4.9248739e-04],
       [1.1905199e-03],
       [3.7345740e-03],
       [5.4698974e-01],
       [9.7069710e-01],
       [4.6250136e-03],
       [7.7226275e-01],
       [6.0423080e-02],
       [2.2497356e-01],
       [9.5734471e-01],
       [9.6661210e-01],
       [5.7181460e-01],
       [8.0467802e-01],
       [2.1298535e-03],
       [2.1654849e-03],
       [8.6465758e-01],
       [1.0797704e-03],
       [9.9955010e-01],
       [9.5008675e-04],
       [8.1563293e-04],
       [8.7853581e-01],
       [4.9543584e-04],
       [3.0278196e-04],
       [9.1569126e-01],
       [3.4434230e-03],
       [6.9965199e-03],
       [9.9933547e-01],
       [9.9783957e-01],
       [7.9944613e-04],
       [4.8600712e-01],
       [9.1467351e-01],
       [9.7699124e-01],
       [2.9100552e-03],
       [2.0354504e-03],
       [9.014239

In [30]:
predictions_classes=np.where(predictions >0.5,1,0)

In [32]:
predictions_classes

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
    


## **Evaluating Model Performance**

So how well did we do? How do we actually measure "well". Is 95% accuracy good enough? It all depends on the situation. Also we need to take into account things like recall and precision. Make sure to watch the video discussion on classification evaluation before running this code!



In [33]:
model.metrics_names

['loss', 'accuracy']

In [34]:
model.evaluate(x=Scaled_X_test,y=y_test)

9/9 [==============================] - 0s 6ms/step - loss: 0.1359 - accuracy: 0.9564


[0.13589628040790558, 0.9563636183738708]

In [35]:
from sklearn.metrics import classification_report,confusion_matrix

In [36]:
confusion_matrix(y_test,predictions_classes)

array([[147,   1],
       [ 11, 116]])

In [37]:
print(classification_report(y_test,predictions_classes))

              precision    recall  f1-score   support

         0.0       0.93      0.99      0.96       148
         1.0       0.99      0.91      0.95       127

    accuracy                           0.96       275
   macro avg       0.96      0.95      0.96       275
weighted avg       0.96      0.96      0.96       275



## Saving and Loading Models

Now that we have a model trained, let's see how we can save and load it.

In [39]:
model.save('myfirstmodel.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [40]:
from keras.models import load_model

In [41]:
newmodel = load_model('myfirstmodel.h5')

In [46]:
#newmodel.predict(X_test)
#Need to change this code according to the new approach